<a href="https://colab.research.google.com/github/beniamine3155/deep_learning_tensorflow/blob/main/4_loss_and_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

## Mean Absolute Error

In [3]:
def mae(y_predicted, y_true):
  total_error = 0
  for yp, yt in zip(y_predicted, y_true):
    total_error += abs(yp - yt)
  print("Total error: ", total_error)
  mae = total_error/ len(y_predicted)
  print("MAE: ", mae)
  return mae

In [4]:
mae(y_predicted, y_true)

Total error:  2.5
MAE:  0.5


0.5

# Implement same thing using numpy

In [5]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [8]:
mae_np(y_predicted, y_true)

0.5

## Log Loss or Binary Cross Entropy

In [9]:
np.log([0])

<ipython-input-9-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([1e-15])

array([-34.53877639])

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
1-epsilon

0.999999999999999

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_predicted_new = np.array(y_predicted_new)

In [17]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [18]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [19]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [20]:

log_loss(y_true, y_predicted)

17.2696280766844