<a href="https://colab.research.google.com/github/beniamine3155/deep_learning_tensorflow/blob/main/tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundamental

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.15.0


## Creating Tensor with tf.constant()



In [4]:
# create a tensor
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
# check the no of dimenson of tensor
scalar.ndim

0

In [6]:
# create a vector (more than 0 dimension)
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# create a matrix (more than 1 dimenson)
matrix = tf.constant([[5, 6],
                      [7, 8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

In [9]:
matrix.ndim

2

In tensor, by default data type is either int32 or float32

In [11]:
# Create another matrix and define the datatype
matrix_a = tf.constant([[5., 8.],
                        [9.,10.],
                        [2., 4.]], dtype = tf.float16)
matrix_a

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 5.,  8.],
       [ 9., 10.],
       [ 2.,  4.]], dtype=float16)>

In [12]:
matrix_a.shape

TensorShape([3, 2])

In [13]:
# more than 2 dimensions

tensor = tf.constant([[ [5, 6],
                       [7, 18]],
                      [ [12, 61],
                       [32, 5]],
                      [ [12, 9],
                       [21, 98]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7, 18]],

       [[12, 61],
        [32,  5]],

       [[12,  9],
        [21, 98]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

TensorShape([3, 2, 2])

## Creating Tensors with tf.Variable()

tf.constant() -> immutable (can't be changed)



tf.Variable() -> mutable (can be changed)



In [16]:
changeable_tensor = tf.Variable([10, 20])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>

In [18]:
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 20], dtype=int32)>

## Create a random tensor

In [20]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [21]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [23]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [25]:
# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7, 18]],

       [[12, 61],
        [32,  5]],

       [[12,  9],
        [21, 98]]], dtype=int32)>

## Others way to make tensor

In [26]:
# create a tensor of all ones
tf.ones(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [27]:
# create a tensor of all zeros
tf.zeros(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
import numpy as np
# create a numpy array
numpy_array = np.arange(1, 25, dtype = np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant(numpy_array, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [30]:
A.ndim

3

In [31]:
A.shape

TensorShape([2, 3, 4])

## Getting information from tensors (shape, rank, size)

In [35]:
# create a rank_4_tensor with 4 dimensions
rank_4_tensor = tf.ones([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [36]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [37]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [38]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [39]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [40]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

## Manipulating tensors (tensor operations)


In [42]:
# we can add value in the tensor using addition operation
tensor = tf.constant([[12, 5], [9, 20]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [ 9, 20]], dtype=int32)>

In [43]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 15],
       [19, 30]], dtype=int32)>

In [44]:
# original tensor can't be changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [ 9, 20]], dtype=int32)>

In [45]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120,  50],
       [ 90, 200]], dtype=int32)>

In [46]:
# subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, -5],
       [-1, 10]], dtype=int32)>

In [47]:
# multiplication function
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 10],
       [18, 40]], dtype=int32)>

In [48]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  5],
       [ 9, 20]], dtype=int32)>

In [49]:
# matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[189, 160],
       [288, 445]], dtype=int32)>

In [50]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[189, 160],
       [288, 445]], dtype=int32)>

In [52]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [53]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

Trying to matrix multiply two tensors with the shape (3, 2)
errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).

Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).

We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.

tf.transpose() - switches the dimensions of a given tensor.

In [55]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [57]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [58]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [59]:
# Try matrix multiplication
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [60]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## Changing the datatype of a tensor

In [61]:
# create a new tensor with default datatype
B = tf.constant([5.3, 7.8]) # float32
C = tf.constant([5, 7]) # int32
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.3, 7.8], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>)

In [62]:
# change datatype float32 to float16
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([5.3, 7.8], dtype=float16)>

In [63]:
# change int32 to float32
C = tf.cast(C, dtype = tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 7.], dtype=float32)>

## Getting the absolute value

In [64]:
# create a tensor with negative value
D = tf.constant([-10, -20])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10, -20], dtype=int32)>

In [66]:
# get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

## Finding the min, max, mean, sum (aggregation)

In [67]:
# create a tensor with 50 random values
Z = tf.constant(np.random.randint(low = 50, high = 100, size = 50))
Z

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 59, 61, 86, 93, 75, 77, 87, 73, 91, 59, 87, 93, 85, 87, 71, 89,
       92, 77, 57, 96, 50, 79, 81, 86, 90, 67, 53, 76, 64, 55, 87, 94, 98,
       96, 58, 97, 55, 84, 78, 65, 55, 53, 52, 90, 95, 54, 59, 94, 52])>

In [68]:
# find the minimum
tf.reduce_min(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [69]:
# find the maximum
tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [70]:
# find the mean
tf.reduce_mean(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=75>

In [71]:
# find the sum
tf.reduce_sum(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=3782>

## Finding the positional maximum and minimum

In [72]:
# find the maximum element position of Z
tf.argmax(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=33>

In [73]:
# find the minimum element position of Z
tf.argmin(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

## Squeezing a tensor (removing all single dimensions)

In [74]:
S = tf.constant(np.random.randint(50, 100, 50), shape=(1,1,1,1,50))
S

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[80, 68, 70, 82, 62, 98, 52, 54, 57, 63, 66, 59, 58, 99, 91,
           88, 79, 91, 92, 80, 79, 58, 89, 67, 65, 54, 54, 85, 73, 77,
           71, 55, 68, 55, 93, 97, 65, 55, 61, 53, 84, 52, 69, 77, 52,
           90, 80, 94, 69, 76]]]]])>

In [75]:
S.ndim, S.shape

(5, TensorShape([1, 1, 1, 1, 50]))

In [76]:
S_squeezed = tf.squeeze(S)
S_squeezed.shape, S_squeezed.ndim

(TensorShape([50]), 1)

## One-hot encoding

In [77]:
num_list = [0,1,2,3]
num_list

[0, 1, 2, 3]

In [78]:
tf.one_hot(num_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [80]:
# custom values for on and off encoding
tf.one_hot(num_list, depth=4, on_value = "X", off_value="Y")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'X', b'Y', b'Y', b'Y'],
       [b'Y', b'X', b'Y', b'Y'],
       [b'Y', b'Y', b'X', b'Y'],
       [b'Y', b'Y', b'Y', b'X']], dtype=object)>

## Squaring, log, square root

In [81]:
G = tf.constant(np.arange(1,10))
G

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [82]:
# Square
tf.square(G)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [83]:
# square root
tf.sqrt(G)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [85]:
# change the datatype
G = tf.cast(G, dtype = tf.float32)
G


<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [86]:
tf.sqrt(G)


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [87]:
# find the log
tf.math.log(G)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Manipulating tf.Variable tensors

In [88]:
# ceeate a variable tensor
H = tf.Variable(np.arange(0,5))
H

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [89]:
# Assign the final value a new value of 50
H.assign([0, 1, 2, 3, 50])
H

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [90]:
# Add 10 to every element in I
H.assign_add([10, 10, 10, 10, 10])
H

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors and NumPy

In [92]:
I = tf.constant(np.array([5. , 7. , 9.]))
I

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([5., 7., 9.])>

In [93]:
np.array(I), type(np.array(I))

(array([5., 7., 9.]), numpy.ndarray)

In [94]:
# Convert tensor I to NumPy with .numpy()
I.numpy(), type(I.numpy())

(array([5., 7., 9.]), numpy.ndarray)

## Using @tf.function

In [95]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [96]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Finding access to GPUs

In [97]:
print(tf.config.list_physical_devices('GPU'))

[]


In [98]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


In [101]:
!pip install --upgrade nvidia-smi


In [102]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
