<a href="https://colab.research.google.com/github/beniamine3155/deep_learning_tensorflow/blob/main/tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundamental

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.15.0


## Creating Tensor with tf.constant()



In [4]:
# create a tensor
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
# check the no of dimenson of tensor
scalar.ndim

0

In [6]:
# create a vector (more than 0 dimension)
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# create a matrix (more than 1 dimenson)
matrix = tf.constant([[5, 6],
                      [7, 8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

In [9]:
matrix.ndim

2

In tensor, by default data type is either int32 or float32

In [11]:
# Create another matrix and define the datatype
matrix_a = tf.constant([[5., 8.],
                        [9.,10.],
                        [2., 4.]], dtype = tf.float16)
matrix_a

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 5.,  8.],
       [ 9., 10.],
       [ 2.,  4.]], dtype=float16)>

In [12]:
matrix_a.shape

TensorShape([3, 2])

In [13]:
# more than 2 dimensions

tensor = tf.constant([[ [5, 6],
                       [7, 18]],
                      [ [12, 61],
                       [32, 5]],
                      [ [12, 9],
                       [21, 98]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7, 18]],

       [[12, 61],
        [32,  5]],

       [[12,  9],
        [21, 98]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

TensorShape([3, 2, 2])

## Creating Tensors with tf.Variable()

tf.constant() -> immutable (can't be changed)



tf.Variable() -> mutable (can be changed)



In [16]:
changeable_tensor = tf.Variable([10, 20])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>

In [18]:
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 20], dtype=int32)>

## Create a random tensor

In [20]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [21]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [23]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [25]:
# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7, 18]],

       [[12, 61],
        [32,  5]],

       [[12,  9],
        [21, 98]]], dtype=int32)>

## Others way to make tensor

In [26]:
# create a tensor of all ones
tf.ones(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [27]:
# create a tensor of all zeros
tf.zeros(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
import numpy as np
# create a numpy array
numpy_array = np.arange(1, 25, dtype = np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant(numpy_array, shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [30]:
A.ndim

3

In [31]:
A.shape

TensorShape([2, 3, 4])

## Getting information from tensors (shape, rank, size)